version: "3.8"
services:
  dev_dca:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    env_file: ./.env
    container_name: dca_php
    volumes:
    - ../../:/app/
    working_dir: /app/
    tty: true
