version: "3.8"
services:
  dca:
    build:
      context: ../../
      dockerfile: Dockerfile
      target: development
    env_file: ../../.env
    volumes:
    - ../../:/app/
    working_dir: /app/
    tty: true
