version: "3.8"
services:
  dca:
    container_name: dev_dca
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    env_file: ./.env
    volumes:
    - ../../:/app/
    working_dir: /app/
    tty: true
